; CHAPO_TILE.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 18
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

IF !DEF(TILES_DEF)
TILES_DEF SET 1

 SECTION "Tiles", HOME

; Start of tile array.
TILES:
; 0
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
; 1
DB $18,$18,$66,$7E,$42,$7E,$99,$E7
DB $99,$E7,$42,$7E,$66,$7E,$18,$18

;************************************************************
;* tile map

SECTION "Map",HOME

HELLO_MAP:
  DB $01,$00,$00,$00,$00,$00,$00
  DB $02

ENDC
; End of CHAPO_TILE.Z80
