; CHAPO_TILE.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Tiles
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 8 x 8
;   Tiles                : 0 to 18
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

IF !DEF(TILES_DEF)
TILES_DEF SET 1

 SECTION "Tiles", HOME

; Start of tile array.
TILES:
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $7E,$7E,$DF,$FF,$BF,$FF,$F7,$EF
DB $FF,$87,$7B,$5D,$29,$57,$3B,$47
DB $1D,$13,$3F,$3F,$2D,$3B,$7B,$7D
DB $FF,$99,$EF,$99,$EF,$99,$C9,$FF
DB $F8,$F8,$74,$CC,$7E,$C2,$7D,$DB
DB $EF,$F1,$E7,$19,$E5,$1B,$EE,$1E
DB $1F,$1F,$14,$1B,$1A,$1D,$1B,$16
DB $1B,$16,$1F,$12,$1F,$12,$16,$1B
DB $0F,$0B,$0B,$0F,$07,$07,$05,$07
DB $02,$03,$07,$07,$0D,$0B,$1F,$1F
DB $F8,$F8,$F0,$F0,$70,$B0,$D0,$30
DB $D0,$30,$D0,$30,$B0,$70,$D0,$30
DB $B0,$70,$E8,$D8,$A8,$D8,$F8,$C8
DB $D8,$E8,$F8,$88,$F8,$18,$F0,$F0
DB $1F,$1F,$3B,$3F,$71,$7F,$7F,$7F
DB $20,$3F,$7F,$7F,$FF,$FF,$27,$3D
DB $5A,$5A,$5A,$5A,$27,$39,$1F,$1C
DB $3F,$3F,$40,$7F,$3F,$3F,$40,$7F
DB $00,$00,$C0,$C0,$F0,$F0,$FC,$FC
DB $3E,$FE,$CE,$FE,$F6,$FE,$3C,$EC
DB $DE,$D2,$D6,$DA,$1F,$E1,$FF,$E1
DB $FF,$F9,$0F,$FD,$F2,$FE,$0C,$FC
DB $3F,$3F,$0D,$0A,$17,$1D,$7A,$7F
DB $FF,$8D,$FF,$8F,$FF,$8D,$7F,$7F
DB $16,$19,$1F,$19,$3F,$3F,$3F,$3B
DB $3F,$24,$1D,$1F,$3D,$3F,$3D,$3F
DB $F0,$F8,$DC,$FC,$3A,$FE,$E1,$F9
DB $F1,$1D,$FB,$1D,$FD,$1F,$F6,$FE
DB $08,$F8,$F8,$F8,$FC,$FC,$FC,$FC
DB $FC,$04,$F8,$F8,$F8,$F8,$F8,$F8
DB $1F,$1F,$1E,$1E,$1E,$1E,$0E,$08
DB $0E,$0E,$0E,$0E,$1A,$1E,$3F,$3D
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $00,$00,$00,$00,$00,$00,$00,$00
DB $F8,$D8,$F8,$F8,$F0,$F0,$70,$40
DB $70,$70,$70,$70,$D0,$F0,$F0,$E0

;************************************************************
;* tile map

SECTION "Map",HOME

HELLO_MAP:
  DB $01,$00,$00,$00,$00,$00,$00
  DB $02

ENDC
; End of CHAPO_TILE.Z80
